language: php

php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - hhvm

env:
  - LARAVEL_VERSION="5.0.*"
  - LARAVEL_VERSION="5.1.*"
  - LARAVEL_VERSION="5.2.*"
  - LARAVEL_VERSION="5.3.*"
  - LARAVEL_VERSION="5.4.*"

# Laravel 5.3+ requires PHP 5.6+
matrix:
  exclude:
    - php: "5.5"
      env: LARAVEL_VERSION="5.3.*"
    - php: "5.5"
      env: LARAVEL_VERSION="5.4.*"

before_script:
  - composer install --dev
  - composer remove --update-with-dependencies illuminate/database illuminate/support
  - composer remove --dev --update-with-dependencies illuminate/events
  - composer require illuminate/database:${LARAVEL_VERSION} illuminate/support:${LARAVEL_VERSION}
  - composer require --dev illuminate/events:${LARAVEL_VERSION}

script:
  - vendor/bin/phpunit
