language: php

php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - hhvm

env:
  - LARAVEL_VERSION="5.0.*"
  - LARAVEL_VERSION="5.1.*"
  - LARAVEL_VERSION="5.2.*"
  - LARAVEL_VERSION="5.3.*"

before_script:
  - composer install --dev
  - composer remove --update-with-dependencies illuminate/database illuminate/support
  - composer remove --dev --update-with-dependencies illuminate/events
  - composer require illuminate/database:${LARAVEL_VERSION} illuminate/support:${LARAVEL_VERSION}
  - composer require --dev illuminate/events:${LARAVEL_VERSION}
