language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Test in supported Laravel versions and Laravel's supported PHP versions.
#
# * Laravel 5.3+ requires PHP 5.6+.
# * Laravel 5.5+ requires PHP 7.0+.
# * Laravel 5.6+ requires PHP 7.1+.
# * Laravel 6.0+ requires PHP 7.2+.
# * Laravel 7.0+ requires PHP 7.2+.
# * TravisCI tests in Ubuntu 16.04 Xenial Xerus, which doesn't support PHP 5.5.
#   Test 5.5 in Trusty Tahr instead.
matrix:
  include:
    - php: "5.5"
      dist: trusty
      env: LARAVEL_VERSION="5.0.*"
    - php: "5.5"
      dist: trusty
      env: LARAVEL_VERSION="5.1.*"
    - php: "5.5"
      dist: trusty
      env: LARAVEL_VERSION="5.2.*"

    - php: "5.6"
      env: LARAVEL_VERSION="5.0.*"
    - php: "5.6"
      env: LARAVEL_VERSION="5.1.*"
    - php: "5.6"
      env: LARAVEL_VERSION="5.2.*"
    - php: "5.6"
      env: LARAVEL_VERSION="5.3.*"
    - php: "5.6"
      env: LARAVEL_VERSION="5.4.*"

    - php: "7.0"
      env: LARAVEL_VERSION="5.0.*"
    - php: "7.0"
      env: LARAVEL_VERSION="5.1.*"
    - php: "7.0"
      env: LARAVEL_VERSION="5.2.*"
    - php: "7.0"
      env: LARAVEL_VERSION="5.3.*"
    - php: "7.0"
      env: LARAVEL_VERSION="5.4.*"
    - php: "7.0"
      env: LARAVEL_VERSION="5.5.*"

    - php: "7.1"
      env: LARAVEL_VERSION="5.0.*"
    - php: "7.1"
      env: LARAVEL_VERSION="5.1.*"
    - php: "7.1"
      env: LARAVEL_VERSION="5.2.*"
    - php: "7.1"
      env: LARAVEL_VERSION="5.3.*"
    - php: "7.1"
      env: LARAVEL_VERSION="5.4.*"
    - php: "7.1"
      env: LARAVEL_VERSION="5.5.*"
    - php: "7.1"
      env: LARAVEL_VERSION="5.6.*"
    - php: "7.1"
      env: LARAVEL_VERSION="5.7.*"

    - php: "7.2"
      env: LARAVEL_VERSION="5.0.*"
    - php: "7.2"
      env: LARAVEL_VERSION="5.1.*"
    - php: "7.2"
      env: LARAVEL_VERSION="5.2.*"
    - php: "7.2"
      env: LARAVEL_VERSION="5.3.*"
    - php: "7.2"
      env: LARAVEL_VERSION="5.4.*"
    - php: "7.2"
      env: LARAVEL_VERSION="5.5.*"
    - php: "7.2"
      env: LARAVEL_VERSION="5.6.*"
    - php: "7.2"
      env: LARAVEL_VERSION="5.7.*"
    - php: "7.2"
      env: LARAVEL_VERSION="5.8.*"
    - php: "7.2"
      env: LARAVEL_VERSION="6.0.*"
    - php: "7.2"
      env: LARAVEL_VERSION="7.0.*"

    - php: "7.3"
      env: LARAVEL_VERSION="5.0.*"
    - php: "7.3"
      env: LARAVEL_VERSION="5.1.*"
    - php: "7.3"
      env: LARAVEL_VERSION="5.2.*"
    - php: "7.3"
      env: LARAVEL_VERSION="5.3.*"
    - php: "7.3"
      env: LARAVEL_VERSION="5.4.*"
    - php: "7.3"
      env: LARAVEL_VERSION="5.5.*"
    - php: "7.3"
      env: LARAVEL_VERSION="5.6.*"
    - php: "7.3"
      env: LARAVEL_VERSION="5.7.*"
    - php: "7.3"
      env: LARAVEL_VERSION="5.8.*"
    - php: "7.3"
      env: LARAVEL_VERSION="6.0.*"
    - php: "7.3"
      env: LARAVEL_VERSION="7.0.*"

    - php: "7.4"
      env: LARAVEL_VERSION="5.0.*"
    - php: "7.4"
      env: LARAVEL_VERSION="5.1.*"
    - php: "7.4"
      env: LARAVEL_VERSION="5.2.*"
    - php: "7.4"
      env: LARAVEL_VERSION="5.3.*"
    - php: "7.4"
      env: LARAVEL_VERSION="5.4.*"
    - php: "7.4"
      env: LARAVEL_VERSION="5.5.*"
    - php: "7.4"
      env: LARAVEL_VERSION="5.6.*"
    - php: "7.4"
      env: LARAVEL_VERSION="5.7.*"
    - php: "7.4"
      env: LARAVEL_VERSION="5.8.*"
    - php: "7.4"
      env: LARAVEL_VERSION="6.0.*"
    - php: "7.4"
      env: LARAVEL_VERSION="7.0.*"

# Code coverage testing isn't necessary, so remove xdebug to speed things up.
before_install:
  - phpenv config-rm xdebug.ini

before_script:
  # Install the right version of Laravel components based on the LARAVEL_VERSION
  # environment variable.
  - 'sed -i -e "s/\"illuminate\/database\": \"\(.*\)\"/\"illuminate\/database\": \"$LARAVEL_VERSION\"/" composer.json'
  - 'sed -i -e "s/\"illuminate\/support\": \"\(.*\)\"/\"illuminate\/support\": \"$LARAVEL_VERSION\"/" composer.json'
  - 'sed -i -e "s/\"illuminate\/events\": \"\(.*\)\"/\"illuminate\/events\": \"$LARAVEL_VERSION\"/" composer.json'
  - composer install --dev

script:
  - vendor/bin/phpunit
